spring:
  application:
    name: web-sync

server:
  port: 9081

# Cassandra Connection info
cassandra:
  contactpoints: 127.0.0.1
  port: 9042
  keyspace: spring_reactive
  basepackages: com.sk.learn

