spring:
  application:
    name: web-async

server:
  port: 9080

# Cassandra Connection info
cassandra:
  contactpoints: 127.0.0.1
  port: 9042
  keyspace: spring_reactive
  basepackages: com.sk.learn
